require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/watchlists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Watchlist. As you add validations to Watchlist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Watchlist.create! valid_attributes
      get watchlists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      watchlist = Watchlist.create! valid_attributes
      get watchlist_url(watchlist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_watchlist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      watchlist = Watchlist.create! valid_attributes
      get edit_watchlist_url(watchlist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Watchlist" do
        expect {
          post watchlists_url, params: { watchlist: valid_attributes }
        }.to change(Watchlist, :count).by(1)
      end

      it "redirects to the created watchlist" do
        post watchlists_url, params: { watchlist: valid_attributes }
        expect(response).to redirect_to(watchlist_url(Watchlist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Watchlist" do
        expect {
          post watchlists_url, params: { watchlist: invalid_attributes }
        }.to change(Watchlist, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post watchlists_url, params: { watchlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested watchlist" do
        watchlist = Watchlist.create! valid_attributes
        patch watchlist_url(watchlist), params: { watchlist: new_attributes }
        watchlist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the watchlist" do
        watchlist = Watchlist.create! valid_attributes
        patch watchlist_url(watchlist), params: { watchlist: new_attributes }
        watchlist.reload
        expect(response).to redirect_to(watchlist_url(watchlist))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        watchlist = Watchlist.create! valid_attributes
        patch watchlist_url(watchlist), params: { watchlist: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested watchlist" do
      watchlist = Watchlist.create! valid_attributes
      expect {
        delete watchlist_url(watchlist)
      }.to change(Watchlist, :count).by(-1)
    end

    it "redirects to the watchlists list" do
      watchlist = Watchlist.create! valid_attributes
      delete watchlist_url(watchlist)
      expect(response).to redirect_to(watchlists_url)
    end
  end
end
